# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'SwiftApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftApp
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Moya'
  pod 'HandyJSON'
  pod 'Kingfisher'
  pod 'MBProgressHUD'
  pod 'Reusable'
#  pod 'LLCycleScrollView'
  pod 'MJRefresh'
  
  target 'SwiftAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftAppUITests' do
    # Pods for testing
  end

end
